import { StyleSheet } from "react-native";
import { backgroundColor } from "react-native/Libraries/Components/View/ReactNativeStyleAttributes";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#eee7dd",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
    color: "#fff",
  },
  btnOpenModal: {
    zIndex: 9,
    backgroundColor: "#00a884",
    width: 50,
    height: 50,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 10,
    right: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 3,
    },
  },
  modalBtnBack: {
    width: 40,
    height: 40,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 5,
    left: 10,
  },
  inputs: {
    backgroundColor: "#fff",
    width: 300,
    height: 40,
    borderRadius: 5,
    paddingLeft: 10,
    marginTop: 15,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 3,
    },
  },
  btnAddProduct: {
    marginTop: 20,
    backgroundColor: "#00a884",
    width: 150,
    height: 50,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 3,
    },
  },
  textAddProduct: { fontWeight: "bold", color: "#fff" },
  total: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    backgroundColor: "#e7ffdb",
    bottom: 10,
    left: 10,
    width: 200,
    height: 50,
    borderRadius: 5,
    zIndex: 9,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 3,
    },
  },
  btnDeleteAllProducts: { zIndex: 9, position: "absolute", right: 10, top: 5 },
});
export default styles;
